[build]
  command = "./netlify.sh"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  PHP_VERSION = "8.2"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset caching
[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
